### ISSUE TITLE
Looking for internships/full-time?

### ISSUE THREAD

**Issue by brotzky** [amanbrar1999/stocks-data#1]
I lead engineering at [Fey](https://feyapp.com/) and we're looking for engineers (Backend | TS/Node). Wondering if either of you would be interested to learn more? I saw that you're both Waterloo students and we're based out of Canada. Or maybe you have friends interested?

**Comment by amanbrar1999** [comment]
Hi Dennis, Thanks for reaching out! 

Unfortunately I am no longer seeking internships at this time, however my friend Tirth (https://github.com/tirthpat1999) is on the lookout for internships and is interested. He is also a senior Waterloo student and I think he would be a great fit. He can be reached through his GitHub or his email tirth.patel@uwaterloo.ca.

**Comment by brotzky** [comment]
Thanks, Aman. I'll reach out. Let me know if you're back on the search anytime.
